package DSMS_CORBA;


/**
* DSMS_CORBA/DSMS_Interface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DSMS_CORBA.idl
* Monday, July 10, 2017 2:08:06 PM EDT
*/

public interface DSMS_Interface extends DSMS_InterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DSMS_Interface
