package DSMS_CORBA;


/**
* DSMS_CORBA/DSMS_InterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DSMS_CORBA.idl
* Monday, July 10, 2017 2:08:06 PM EDT
*/

public interface DSMS_InterfaceOperations 
{
  String createTRecord (String managerID, String firstName, String lastName, String address, String phone, String specialization, String location);
  String createSRecord (String managerID, String firstName, String lastName, String courseRegistered, String status, String statusDate);
  String getRecordCounts (String managerID);
  String editRecord (String managerID, String recordID, String fieldName, String newValue);
  String transferRecord (String managerID, String recordID, String remoteClinicServerName);
} // interface DSMS_InterfaceOperations
