package DSMS_CORBA;


/**
* DSMS_CORBA/DSMS_InterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DSMS_CORBA.idl
* Monday, July 10, 2017 2:08:06 PM EDT
*/

abstract public class DSMS_InterfaceHelper
{
  private static String  _id = "IDL:DSMS_CORBA/DSMS_Interface:1.0";

  public static void insert (org.omg.CORBA.Any a, DSMS_CORBA.DSMS_Interface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DSMS_CORBA.DSMS_Interface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DSMS_CORBA.DSMS_InterfaceHelper.id (), "DSMS_Interface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DSMS_CORBA.DSMS_Interface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DSMS_InterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DSMS_CORBA.DSMS_Interface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DSMS_CORBA.DSMS_Interface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DSMS_CORBA.DSMS_Interface)
      return (DSMS_CORBA.DSMS_Interface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DSMS_CORBA._DSMS_InterfaceStub stub = new DSMS_CORBA._DSMS_InterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DSMS_CORBA.DSMS_Interface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DSMS_CORBA.DSMS_Interface)
      return (DSMS_CORBA.DSMS_Interface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DSMS_CORBA._DSMS_InterfaceStub stub = new DSMS_CORBA._DSMS_InterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
