package DSMS_CORBA;


/**
* DSMS_CORBA/DSMS_Interface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/chongli/Github/asg2/src/DSMS_CORBA.idl
* Sunday, July 9, 2017 11:20:32 o'clock PM EDT
*/

public interface DSMS_Interface extends DSMS_InterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DSMS_Interface
