package DSMS_CORBA;


/**
* DSMS_CORBA/DSMS_InterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/chongli/Github/asg2/src/DSMS_CORBA.idl
* Sunday, July 9, 2017 11:20:32 o'clock PM EDT
*/

public interface DSMS_InterfaceOperations 
{

  /**
       	* Operation createTRecord
       	*/
  String createTRecord (String managerID, String firstName, String lastName, String address, String phone, String specialization, String location);

  /**
       	* Operation createSRecord
       	*/
  String createSRecord (String managerID, String firstName, String lastName, String courseRegistered, String status, String statusDate);

  /**
       	* Operation getRecordCounts
       	*/
  String getRecordCounts (String managerID);

  /**
       	* Operation editRecord
      	*/
  String editRecord (String managerID, String recordID, String fieldName, String newValue);

  /**
       	* Operation transferRecord
       	*/
  String transferRecord (String managerID, String recordID, String remoteClinicServerName);
} // interface DSMS_InterfaceOperations
